spring.application.name=demo

management.endpoints.web.exposure.include = *

#management.endpoints.web.exposure.include= health, info
management.info.env.enabled = true

info.app.name = demo app
info.app.cooldetail = testing to see if u can put anything
info.app.version = 10.0.5

info.yoyo.id = 5